# Решение задачи линейного программирования
Тушавин В. А.  
20 ноября 2015 г.  

### Постановка задачи


Николай Кузнецов управляет небольшим механическим заводом. В будущем месяце он планирует изготавливать два продукта (А и В), по которым удельная маржинальная прибыль оценивается в 2500 и 3500 руб., соответственно.

Изготовление обоих продуктов требует затрат на машинную обработку, сырье и труд На изготовление каждой единицы продукта А отводится 3 часа машинной обработки, 16 единиц сырья и 6 единиц труда. Соответствующие требования к единице продукта В составляют 10, 4 и 6. Николай прогнозирует, что в следующем месяце он может предоставить 330 часов машинной обработки, 400 единиц сырья и 240 единиц труда. Технология производственного процесса такова, что не менее 12 единиц продукта В необходимо изготавливать в каждый конкретный месяц.

Наименование ресурса | A  | B  | Объем ресурсов
---------------------|----|----|---------------
Часы маш.обработки   |  3 | 10 |  330
Единиц сырья         | 16 |  4 |  400
Единиц труда         |  6 |  6 |  240


Николай хочет построить модель с тем, чтобы определить количество единиц продуктов А и В, которые он доложен производить в следующем месяце для максимизации маржинальной прибыли.

### Решение задачи
#### Этап 1. Определение переменных

Существует целевая переменная (обозначим её Z), которую необходимо оптимизировать, то есть максимизировать или минимизировать (например, прибыль, выручка или расходы). Николай стремится максимизировать маржинальную прибыль, следовательно, целевая переменная:

Z --- это суммарная маржинальная прибыль (в рублях), полученная в следующем месяце в результате производства продуктов А и В.

Существует ряд неизвестных искомых переменных (обозначим их х~1~, х~2~, х~3~ и пр.), чьи значения необходимо определить для получения оптимальной величины целевой функции, которая, в нашем случае является суммарной маржинальной прибылью. Эта маржинальная прибыль зависит от количества произведенных продуктов А и В. Значения этих величин необходимо рассчитать, и поэтому они представляют собой искомые переменные в модели. Итак, обозначим:

х~1~ --- количество единиц продукта А, произведенных в следующем месяце.

х~2~ --- количество единиц продукта В, произведенных в следующем месяце.

Очень важно четко определить все переменные величины; особое внимание уделите единицам измерения и периоду времени, к которому относятся переменные.

### Этап. 2. Построение целевой функции

Целевая функция --- это линейное уравнение, которое должно быть или максимизировано или минимизировано. Оно содержит целевую переменную, выраженную с помощью искомых переменных, то есть Z выраженную через х~1~, х~2~, ... в виде линейного уравнения.

В нашем примере каждый изготовленный продукт А приносит 2500 руб. маржинальной прибыли, а при изготовлении х~1~ единиц продукта А, маржинальная прибыль составит 2500х~1~. Аналогично маржинальная прибыль от изготовления х~2~ единиц продукта В составит 3500х~2~. Таким образом, суммарная маржинальная прибыль, полученная в следующем месяце за счет производства х~1~ единиц продукта А и х~2~ единиц продукта В, то есть, целевая переменная Z составит: Z = 2500х~1~+3500х~2~.

Николай стремится максимизировать этот показатель. Таким образом, целевая функция в нашей модели:

$$Z = 2500 х_1 + 3500 х_2 \to \max $$

### Этап. 3. Определение ограничений

Ограничения – это система линейных уравнений и/или неравенств, которые ограничивают величины искомых переменных. Они математически отражают доступность ресурсов, технологические факторы, условия маркетинга и иные требования. Ограничения могут быть трех видов: «меньше или равно», «больше или равно», «строго равно».

В нашем примере для производства продуктов А и В необходимо время машинной обработки, сырье и труд, и доступность этих ресурсов ограничена. Объемы производства этих двух продуктов (то есть значения х~1~ и х~2~) будут, таким образом, ограничены тем, что количество ресурсов, необходимых в производственном процессе, не может превышать имеющееся в наличии. Рассмотрим ситуацию со временем машинной обработки. Изготовление каждой единицы продукта А требует трех часов машинной обработки, и если изготовлено х~1~, единиц, то будет потрачено Зх~1~, часов этого ресурса.

Изготовление каждой единицы продукта В требует 10 часов и, следовательно, если произведено х~2~ продуктов, то потребуется 10х~2~ часов. Таким образом, общий объем машинного времени, необходимого для производства х~1~ единиц продукта А и х~2~ единиц продукта В, составляет 3х~1~+10х~2~. Это общее значение машинного времени не может превышать 330 часов. Математически это записывается следующим образом:

3х~1~+10х~2~≤330

Аналогичные соображения применяются к сырью и труду, что позволяет записать еще два ограничения:

16х~1~+4х~2~≤400

6х~1~+6х~2~≤240

Наконец следует отметить, что существует условие, согласно которому должно быть изготовлено не менее 12 единиц продукта В:

х~2~≥12

#### Этап. 4. Запись условий неотрицательности

Искомые переменные не могут быть отрицательными числами, что необходимо записать в виде неравенств х~1~≥0 и х~2~≥0. В нашем примере второе условия является избыточным, так как выше было определено, что х~2~ не может быть меньше 12.

Полная модель линейного программирования для производственной задачи Николая может быть записана в виде:

$$Z = 2500 х_1 + 3500 х_2 \to \max $$

$$\left\{ {\begin{array}
{3{x_1} + 10{x_2} \le 330}\\
{16{x_1} + 4{x_2} \le 400}\\
{6{x_1} + 6{x_2} \le 240}\\
{{x_1} \ge 0}\\
{{x_2} \ge 12}
\end{array}} \right.$$

### Решение в R

Для решения задач линеного программирования в GNU R можно использовать
следующие пакеты:

- lpSolve
- linprog

Второй пакет является надстройкой над первым и позволяет выводить больше диагностической
информации




#### Решение с пакетом lpSolve



```r
library(lpSolve) # Подключили библиотеку
f.obj <- c(2500, 3500) # Описали целевую функцию
names(f.obj) <-c("A","B")
a.mat<-rbind(c(3,10), # матрица
             c(16,4),   # коээфициентов
             c(6,6),    # при ограничениях
             c(1,0),
             c(0,1))   
a.dir<-c("<=","<=","<=",">=",">=")
b.vec<-c(330,400,240,0,12) # вектор ограничений

result<-lp ("max", f.obj, a.mat, a.dir, b.vec)
```

#### Результат



```r
result
```

```
## Success: the objective function is 130000
```

```r
result$solution
```

```
## [1] 10 30
```

Таким образом, максимальное значение целевой функции равно 130000 и оно достигается при x~1~ и x~2~ равными, соответственно: 10 и 30.

#### Решение с пакетом linprog

Поскольку пакет *linprog* является дополнением к предыдущему пакету, то переменные уже все инициализированы.



```r
library(linprog)
```

```
## Warning: package 'linprog' was built under R version 3.2.2
```

```r
(result<-solveLP( f.obj, b.vec, a.mat, TRUE,const.dir=a.dir,lpSolve=T))
```

```
## 
## 
## Results of Linear Programming / Linear Optimization
## (using lpSolve)
## 
## Objective function (Maximum): 130000 
## 
## Solution
##   opt
## A  10
## B  30
## 
## Constraints
##   actual dir bvec free
## 1    330  <=  330    0
## 2    280  <=  400  120
## 3    240  <=  240    0
## 4     10  >=    0   10
## 5     30  >=   12   18
```

Результат получился тот же, дополнительно выведена информация по свободным ресурсам. 
Таким образом,GNU R предоставляет достаточно удобный механизм для решения задач линейного программирования.

#### Графическое представление решения


```r
source("plot1.R")
```

![](lp01_files/figure-html/unnamed-chunk-4-1.png) 


#### Информация о параметрах R


```r
sessionInfo()
```

```
## R version 3.2.0 (2015-04-16)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1
## 
## locale:
## [1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
## [3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
## [5] LC_TIME=Russian_Russia.1251    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] linprog_0.9-2  lpSolve_5.6.11
## 
## loaded via a namespace (and not attached):
##  [1] magrittr_1.5    tools_3.2.0     htmltools_0.2.6 yaml_2.1.13    
##  [5] stringi_0.4-1   rmarkdown_0.6.1 knitr_1.10.5    stringr_1.0.0  
##  [9] digest_0.6.8    evaluate_0.8
```

